// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  dsa: [{type: 'autogenerated', dirName: 'dsa'}],
  lld: [{type: 'autogenerated', dirName: 'lld'}],  
   
};

module.exports = sidebars;
